-- USE DATABASE 
USE labuser_database;

-- LAST MODIFIED TABLE FOR DIM_CALENDAR
CREATE TABLE DIM_CALENDAR_LAST_MODIFIED(
LAST_MODIFIED_DATE DATE,
LAST_MODIFIED_TS TIMESTAMP);

-- LAST MODIFIED TABLE FOR DIM_CALL_CENTER
CREATE TABLE DIM_CALL_CENTER_LAST_MODIFIED(
LAST_MODIFIED_DATE DATE,
LAST_MODIFIED_TS TIMESTAMP);

-- LAST MODIFIED TABLE FOR DIM_CASE_PRIORITY
CREATE TABLE DIM_CASE_PRIORITY_LAST_MODIFIED(
LAST_MODIFIED_DATE DATE,
LAST_MODIFIED_TS TIMESTAMP);

-- LAST MODIFIED TABLE FOR DIM_CASE_CATEGORY
CREATE TABLE DIM_CASE_CATEGORY_LAST_MODIFIED(
LAST_MODIFIED_DATE DATE,
LAST_MODIFIED_TS TIMESTAMP);

-- LAST MODIFIED TABLE FOR DIM_CASE_COUNTRY
CREATE TABLE DIM_CASE_COUNTRY_LAST_MODIFIED(
LAST_MODIFIED_DATE DATE,
LAST_MODIFIED_TS TIMESTAMP);

-- LAST MODIFIED TABLE FOR DIM_EMPLOYEE
CREATE TABLE DIM_EMPLOYEE_LAST_MODIFIED(
LAST_MODIFIED_DATE DATE,
LAST_MODIFIED_TS TIMESTAMP);

-- LAST MODIFIED TABLE FOR DIM_PRODUCT
CREATE TABLE DIM_PRODUCT_LAST_MODIFIED(
LAST_MODIFIED_DATE DATE,
LAST_MODIFIED_TS TIMESTAMP);

-- LAST MODIFIED TABLE FOR SURVEY_LKP
CREATE TABLE SURVEY_LKP_LAST_MODIFIED(
LAST_MODIFIED_DATE DATE,
LAST_MODIFIED_TS TIMESTAMP);

-- LAST MODIFIED TABLE FOR FACT_CASE
CREATE TABLE FACT_CASE_LAST_MODIFIED(
LAST_MODIFIED_DATE DATE,
LAST_MODIFIED_TS TIMESTAMP);

-- LAST MODIFIED TABLE FOR FACT_SURVEY
CREATE TABLE FACT_SURVEY_LAST_MODIFIED(
LAST_MODIFIED_DATE DATE,
LAST_MODIFIED_TS TIMESTAMP);

-- PROCEDURE TO UPDATE LAST_MODIFIED TABLE
DELIMITER //
CREATE PROCEDURE UPDATE_LAST_MODIFIED_DATE (IN TAB_NAME VARCHAR(25))
BEGIN
	SET @Q1 = CONCAT('TRUNCATE ', TAB_NAME, '_LAST_MODIFIED');
    SET @Q2 = CONCAT('INSERT INTO ',TAB_NAME, '_LAST_MODIFIED SELECT date(max(row_insertion_dttm)) last_modified_date, max(row_insertion_dttm) last_modified_ts FROM ', TAB_NAME);
    PREPARE TRUNCATE_COMM FROM @Q1;
    EXECUTE TRUNCATE_COMM;
    DEALLOCATE PREPARE TRUNCATE_COMM;
    PREPARE INSERT_COMM FROM @Q2;   
    EXECUTE INSERT_COMM;
    DEALLOCATE PREPARE INSERT_COMM;    
END//