CREATE DATABASE IF NOT EXISTS LABUSER_DATABASE;

-- USE DATABASE 
USE LABUSER_DATABASE;

-- CREATE EDUREKA_735821_FUTURECART_CALENDAR_DETAILS
CREATE TABLE IF NOT EXISTS EDUREKA_735821_FUTURECART_CALENDAR_DETAILS(
CALENDAR_DATE DATE,
DATE_DESC VARCHAR(50),
WEEK_DAY_NBR TINYINT,
WEEK_NUMBER SMALLINT,
WEEK_NAME VARCHAR(50),
YEAR_WEEK_NUMBER INT,
MONTH_NUMBER TINYINT,
MONTH_NAME VARCHAR(50),
QUARTER_NUMBER TINYINT,
QUARTER_NAME VARCHAR(50),
HALF_YEAR_NUMBER TINYINT,
HALF_YEAR_NAME VARCHAR(50),
GEO_REGION_CD CHAR(2),
ROW_INSERTION_DTTM TIMESTAMP DEFAULT NOW(),
CONSTRAINT PK_EDUREKA_735821_FUTURECART_CALENDAR_DETAILS PRIMARY KEY (CALENDAR_DATE));

-- CREATE EDUREKA_735821_FUTURECART_CALL_CENTER_DETAILS
CREATE TABLE IF NOT EXISTS EDUREKA_735821_FUTURECART_CALL_CENTER_DETAILS(
CALL_CENTER_ID VARCHAR(10),
CALL_CENTER_VENDOR VARCHAR(50),
LOCATION VARCHAR(50),
COUNTRY VARCHAR(50),
ROW_INSERTION_DTTM TIMESTAMP DEFAULT NOW(),
CONSTRAINT PK_EDUREKA_735821_FUTURECART_CALL_CENTER_DETAILS PRIMARY KEY (CALL_CENTER_ID));

-- CREATE EDUREKA_735821_FUTURECART_CASE_PRIORITY_DETAILS
CREATE TABLE IF NOT EXISTS EDUREKA_735821_FUTURECART_CASE_PRIORITY_DETAILS(
PRIORITY_KEY VARCHAR(5),
PRIORITY VARCHAR(20),
SEVERITY VARCHAR(100),
SLA VARCHAR(2),
ROW_INSERTION_DTTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT PK_EDUREKA_735821_FUTURECART_CASE_PRIORITY_DETAILS PRIMARY KEY (PRIORITY_KEY)); 

-- CREATE EDUREKA_735821_FUTURECART_CASE_CATEGORY_DETAILS
CREATE TABLE IF NOT EXISTS EDUREKA_735821_FUTURECART_CASE_CATEGORY_DETAILS(
CATEGORY_KEY VARCHAR(10),
SUB_CATEGORY_KEY VARCHAR(10),
CATEGORY_DESCRIPTION VARCHAR(50),
SUB_CATEGORY_DESCRIPTION VARCHAR(50),
PRIORITY VARCHAR(5),
ROW_INSERTION_DTTM TIMESTAMP DEFAULT NOW(),
CONSTRAINT PK_EDUREKA_735821_FUTURECART_CASE_CATEGORY_DETAILS PRIMARY KEY (CATEGORY_KEY, SUB_CATEGORY_KEY),
CONSTRAINT FK_PRIORITY FOREIGN KEY (PRIORITY) REFERENCES EDUREKA_735821_FUTURECART_CASE_PRIORITY_DETAILS(PRIORITY_KEY) ON UPDATE CASCADE ON DELETE RESTRICT);

-- CREATE TABLE EDUREKA_735821_FUTURECART_CASE_COUNTRY_DETAILS
CREATE TABLE IF NOT EXISTS EDUREKA_735821_FUTURECART_CASE_COUNTRY_DETAILS(
ID INT,
NAME VARCHAR(75),
ALPHA_2 VARCHAR(2) UNIQUE,
ALPHA_3 VARCHAR(3),
ROW_INSERTION_DTTM TIMESTAMP DEFAULT NOW(),
CONSTRAINT PK_EDUREKA_735821_FUTURECART_CASE_COUNTRY_DETAILS PRIMARY KEY (ID));

-- CREATE EDUREKA_735821_FUTURECART_EMPLOYEE_DETAILS
CREATE TABLE IF NOT EXISTS EDUREKA_735821_FUTURECART_EMPLOYEE_DETAILS(
EMP_KEY INT,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
EMAIL VARCHAR(50),
GENDER CHAR(1),
LDAP VARCHAR(10),
HIRE_DATE DATE,
MANAGER INT,
ROW_INSERTION_DTTM TIMESTAMP DEFAULT NOW(),
CONSTRAINT PK_EDUREKA_735821_FUTURECART_EMPLOYEE_DETAILS PRIMARY KEY (EMP_KEY),
CONSTRAINT FK_HIRE_DATE FOREIGN KEY (HIRE_DATE) REFERENCES EDUREKA_735821_FUTURECART_CALENDAR_DETAILS(CALENDAR_DATE) ON UPDATE CASCADE ON DELETE RESTRICT);

-- CREATE EDUREKA_735821_FUTURECART_PRODUCT_DETAILS
CREATE TABLE IF NOT EXISTS EDUREKA_735821_FUTURECART_PRODUCT_DETAILS(
PRODUCT_ID INT,
DEPARTMENT VARCHAR(50),
BRAND VARCHAR(50),
COMMODITY_DESC VARCHAR(100),
SUB_COMMODITY_DESC VARCHAR(100),
ROW_INSERTION_DTTM TIMESTAMP DEFAULT NOW(),
CONSTRAINT PK_EDUREKA_735821_FUTURECART_PRODUCT_DETAILS PRIMARY KEY (PRODUCT_ID));

-- CREATE EDUREKA_735821_FUTURECART_SURVEY_QUESTION_DETAILS
CREATE TABLE IF NOT EXISTS EDUREKA_735821_FUTURECART_SURVEY_QUESTION_DETAILS(
QUESTION_ID VARCHAR(5),
QUESTION_DESC VARCHAR(200),
RESPONSE_TYPE VARCHAR(20),
RESPONSE_RANGE VARCHAR(10),
NEGATIVE_RESPONSE_RANGE VARCHAR(10),
NEUTRAL_RESPONSE_RANGE VARCHAR(10),
POSITIVE_RESPONSE_RANGE VARCHAR(10),
ROW_INSERTION_DTTM TIMESTAMP DEFAULT NOW(),
CONSTRAINT PK_EDUREKA_735821_FUTURECART_SURVEY_QUESTION_DETAILS PRIMARY KEY (QUESTION_ID));

-- CREATE FACT CASE
CREATE TABLE IF NOT EXISTS FACT_CASE(
CASE_NO INT,
CREATE_TIMESTAMP TIMESTAMP,
LAST_MODIFIED_TIMESTAMP TIMESTAMP,
CREATED_EMPLOYEE_KEY INT,
CALL_CENTER_ID VARCHAR(10),
STATUS VARCHAR(10),
CATEGORY VARCHAR(10),
SUB_CATEGORY VARCHAR(10),
COMMUNICATION_MODE VARCHAR(50),
COUNTRY_CD VARCHAR(2),
PRODUCT_CODE INT,
ROW_INSERTION_DTTM TIMESTAMP DEFAULT NOW(),
CONSTRAINT PK_FACT_CASE PRIMARY KEY (CASE_NO, STATUS, LAST_MODIFIED_TIMESTAMP), 
CONSTRAINT FK_CREATED_EMPLOYEE FOREIGN KEY (CREATED_EMPLOYEE_KEY) REFERENCES EDUREKA_735821_FUTURECART_EMPLOYEE_DETAILS(EMP_KEY) ON UPDATE CASCADE ON DELETE SET NULL,
CONSTRAINT FK_CALL_CENTER FOREIGN KEY (CALL_CENTER_ID) REFERENCES EDUREKA_735821_FUTURECART_CALL_CENTER_DETAILS(CALL_CENTER_ID) ON UPDATE CASCADE ON DELETE RESTRICT,
CONSTRAINT FK_CATEGORY FOREIGN KEY (CATEGORY) REFERENCES EDUREKA_735821_FUTURECART_CASE_CATEGORY_DETAILS(CATEGORY_KEY) ON UPDATE CASCADE ON DELETE RESTRICT,
CONSTRAINT FK_PRODUCT FOREIGN KEY (PRODUCT_CODE) REFERENCES EDUREKA_735821_FUTURECART_PRODUCT_DETAILS(PRODUCT_ID) ON UPDATE CASCADE ON DELETE RESTRICT);

-- CREATE FACT SURVEY
CREATE TABLE IF NOT EXISTS FACT_SURVEY(
SURVEY_ID VARCHAR(10),
CASE_NO INT,
SURVEY_TIMESTAMP TIMESTAMP,
Q1 VARCHAR(2),
Q2 VARCHAR(2),
Q3 VARCHAR(2),
Q4 VARCHAR(2),
Q5 VARCHAR(2),
ROW_INSERTION_DTTM TIMESTAMP DEFAULT NOW());